googlemaps/js-api-loader

- examples/index.html
- package-lock.json
- package.json
- rollup.config.js
- src/index.test.ts
- src/index.ts
- tsconfig.json
This change converts the Loader class to a singleton. Probably should have done this from the start.
closes #90
> feat: change to singleton and fix resolve error

- package-lock.json
- package.json
- src/index.ts
`index.umd.js` is now 24kb
Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #97 🦕
> refactor: replace lodash isEqual with fast-deep-equal

- README.md
Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #95 🦕
> docs: fix incorrect how to contribute link in readme

- src/index.test.ts
- src/index.ts
The singleton loader will retry on script failures up to `retries` attempts. A new instance will not retry again.
closes #93
> feat: add retries

- src/index.test.ts
- src/index.ts
Fixes #101 🦕
Will not reset the retry mechanism until all retry attempts have been exhausted.
> feat: reset retry mechanism on failure with next loader

- src/index.test.ts
- src/index.ts
> fix: loader must not reset if successfully loaded

- CONTRIBUTING.md
- src/index.ts
In this PR:
* Update documentation for `language` to match the example provided
* Fix spacing, numbering, TOC in `CONTRIBUTING.md`
Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #160  🦕
> docs: update language option documentaion

- src/index.test.ts
- src/index.ts
The `onerrorEvent` wasn't being cleared internally. In some cases using the private interface in certain failure modes, this would prevent successful loading of the API.
> fix: clear onerror

- README.md
- examples/index.html
- src/index.test.ts
- src/index.ts
closes #224 by resolving to `window.google`
```javascript
loader
.load()
.then((google) => {
new google.maps.Map(document.getElementById("map"), mapOptions);
})
.catch(e => {
// do something
});
```
> feat: resolve window.google

- src/index.test.ts
- src/index.ts
closes #350 
Also narrows `Event` to `ErrorEvent` in callback signature.
> fix: reject with error, not event

- src/index.test.ts
- src/index.ts
Allow access to a `LoaderStatus` enum with `Loader.status`.
> feat: add status getter

- src/index.test.ts
- src/index.ts
https://developers.google.com/maps/documentation/javascript/load-maps-js-api#dynamic-library-import
> feat: Adopt the inline bootstrap loader

- README.md
- examples/index.html
- src/index.test.ts
- src/index.ts
> fix: Support for Advanced markers (AdvancedMarkerView)

- jest.config.js
- package-lock.json
- package.json
- rollup.config.js
- src/index.test.ts
- tsconfig.json
- typedoc.js
Manually update all dependencies.
> chore: npm update

- src/index.test.ts
- src/index.ts
This PR adds `loading=async` as a combination with the `callback` parameter to resolve the warning message.
From the Discord:
> hello, do you guys know how to get rid off the warning below while using APIProvider component from '@vis.gl/react-google-maps' ? I don't see there any flag to set regarding loading type, obviously I could load the maps in old vanilla JS way but it's not a point while I have installed the library package 😦 
> "Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading"
From the documentation:
> loading: The code loading strategy that the Maps JavaScript API can use. Set to async to indicate that the Maps JavaScript API has not …
> fix: add loading=async to the urls with callbacks

- package.json
- rollup.config.mjs
Don't have the time to investigate why this happened right now, but for some reason webpack needs a .mjs file extension for esm files. Maybe this was caused by adding `"type": "commonjs"` to the package.json?
Fixes the webpack error-message reported by @samuelcole and @martincostello in #825.
> fix: change filename for esm build to use .mjs extension

- src/index.test.ts
- src/index.ts
https://github.com/googlemaps/js-api-loader/issues/809
Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #809
> Fix: a timing issue for sequential importLibrary calls

- package-lock.json
- package.json
- rollup.config.mjs
- tsconfig.build.json
This is a full refactoring of the rollup configuration to speed up builds, simplify the configuration, prevent warnings and fix an error with the generated source maps.
In detail:
- refactor: Combine the three non-esm outputs into a single configuration.
- refactor: add `{babelHelpers:'bundled'}` to configuration. This doesn't change the behavior (since it's the default if unspecified), but it prevents the corresponding warning from showing up.
- feat: Enabled source-maps for all build outputs.
- fix: Use a separate TypeScript configuration (`tsconfig.build.json`) during build. This configuration only compiles the required typescript files and doesn't reproduce the directory structure in the dist-folder (see also the change in package.json). It also now generates source maps correctly …
> fix: rollup/typescript configuration

- .github/workflows/docs.yml
My previous PR surfaced another issue: the docs.yml workflow now needs extra permissions to be able to write to the gh-pages branch. This PR should fix that.
> chore: add contents:write permission for pushing to gh-pages

- MIGRATION.md
- README.md
Fixes a misrepresentation of how libraries are loaded.
closes #1088.
> docs: update documentation regarding library loading
